---
- name: Provision VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
    - import_tasks: ansible/ejercicio1/main.yml
    #- import_tasks: ansible/ejercicio2/main.yml