- name: Instalar dependencias de python
  apt:
    name:
      - python3
      - python3-pip
      - python3-flask
      - gunicorn
    state: present
    update_cache: yes

-
- name: Crear directorio para apliocacion Flask
  file:
    path: /opt/flask-application/
    state: directory
    mode: '0755'

- name: Copiar apliacion de Flask
  copy:
    src: ansible/ejercicio3/{{ item }}
    dest: /opt/flask-application/{{ item }}
    group: admin
    mode: '0750'
  loop:
    - greeting.py
    - wsgi.py

- name: Copiar archivo de unidad systemd para greeting.py en multiples instancias
  template:
    src: templates/greeting.service.j2
    dest: /etc/systemd/system/greeting_{{ item.port }}.service
  loop:
    - { port: 5000 }
    - { port: 5001 }
    - { port: 5002 }
    - { port: 5003 }

- name: Iniciar y habilitar la aplicaciòn greeting.py
  systemd:
    name: greeting_{{ item }}.service
    daemon_reload: yes
    state: started
    enabled: yes
  loop:
    - 5000
    - 5001
    - 5002
    - 5003

- name: Configurar Nginx como balanceador de carga
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Reiniciar Nginx
  