- name: Instalar dependencias de python
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Instalar Flask y Gunicorn
  pip:
    name:
      - flask
      - gunicorn
    state: present
    