- name: Instalar Prometheus y Node Exporter
  apt:
    name: 
      - prometheus
      - prometheus-node-exporter
      - wget
      - tar
    state: present
    update_cache: yes

- name: Instalar dependencias necesarias
  pip:
    name: 
      - flask
      - prometheus-flask-exporter
      - gunicorn
    state: present
    update_cache: yes


- name: Crear directorio para Prometheus
  file:
    path: /etc/prometheus
    state: directory
    mode: '0755'

- name: Configurar promethues
  template:
    src: templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: devuser
    group: admin
    mode: 0644
  notify:
    - Reiniciar Prometheus

- name: Configurar alertas en Prometheus
  copy:
    src: templates/rules.yml.j2
    dest: /etc/prometheus/rules.yml
  notify:
    - Reiniciar Prometheus

- name: Instalar Grafana
  shell: |
    sudo wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
    sudo add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
    sudo apt update -qq >/dev/null
    sudo apt install -qq -y grafana >/dev/null

- name: Configurar puertos 
  ufw:
    rule: allow
    port: {{ item }}
    proto: tcp
  loop:
    - 9090  
    - 3000  
    - 9100  
  notify: Reiniciar UFW

- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
