- name: Instalar Nginx
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: Crear directorio para certificados SSL
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'

- name: Generar clave privada para SSL
  openssl_privatekey:
    path: /etc/nginx/ssl/nginx-key.key
    size: 2048
    state: present

- name: Generar solicitud de firma de certificado (CSR)
  openssl_csr:
    path: /etc/nginx/ssl/nginx-key.csr
    privatekey_path: /etc/nginx/ssl/nginx-key.key
    common_name: "siok.com"
    organization_name: "siok"
    country_name: "PE"
    state: present

- name: Generar certificado SSL autofirmado
  openssl_certificate:
    provider: selfsigned
    selfsigned_not_after: "+365d"
    path: /etc/nginx/ssl/nginx-key.crt
    privatekey_path: /etc/nginx/ssl/nginx-key.key
    csr_path: /etc/nginx/ssl/nginx-key.csr
    state: present

- name: Configurar Nginx para SSL
  template:
    src: templates/nginx_ssl.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: '0664'
  notify: Reiniciar Nginx

- name: Copiar certificado SSL al directorio de certificados confiables
  copy:
    src: /etc/nginx/ssl/nginx-key.crt
    dest: /usr/local/share/ca-certificates/nginx-key.crt
    owner: root
    group: root
    mode: '0644'
    remote_src: yes

- name: Actualizar los certificados confiables
  command: update-ca-certificates
  register: update_certificates_result

- name: Instalar UFW
  apt:
    name: ufw 
    state: present
    update_cache: yes

- name: Habilitar UFW
  ufw:
    state: enabled

- name: Permitir tráfico SSH
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Permitir tráfico HTTP y HTTPS
  ufw:
    rule: allow
    name: "Nginx Full"
