---
- name: Instalar Nginx
  apt:
    update_cache: yes
    name:
      - nginx
    state: present

- name: Generar certificado SSL autofirmado
  shell: |
    openssl genrsa -out private.key 1024
    openssl req -new -x509 -key private.key -out certificate.crt -days 365